title: Jonathan Niemi # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Art, Design, & Programming
  <br><br>
  <a href="https://www.linkedin.com/in/jontniemi/">LinkedIn</a> 
  <br><br>
  (WIP)
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
